ALTER TABLE animais ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE animais ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE animais ADD COLUMN IF NOT EXISTS disponivel_adocao BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE animais DROP COLUMN IF EXISTS ideal_casa;
ALTER TABLE animais DROP COLUMN IF EXISTS gosta_crianca;
ALTER TABLE animais DROP COLUMN IF EXISTS cao_guarda;
ALTER TABLE animais DROP COLUMN IF EXISTS brincalhao;
ALTER TABLE animais DROP COLUMN IF EXISTS necessidade_correr;
ALTER TABLE animais DROP COLUMN IF EXISTS queda_pelo;
ALTER TABLE animais DROP COLUMN IF EXISTS tende_latir;