DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adocao_status') THEN
            CREATE TYPE adocao_status AS ENUM (
                'PENDENTE',
                'EM_ANALISE',
                'APROVADO',
                'RECUSADO',
                'FINALIZADO'
                );
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'animal_sexo') THEN
            CREATE TYPE animal_sexo AS ENUM (
                'FEMEA',
                'MACHO'
                );
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'animal_pelagem') THEN
            CREATE TYPE animal_pelagem AS ENUM (
                'CURTA',
                'MEDIA',
                'LONGA',
                'ENCARACOLADA',
                'DURA',
                'SEDOSA',
                'LANOSA'
                );
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'animal_porte') THEN
            CREATE TYPE animal_porte AS ENUM (
                'PEQUENO',
                'MEDIO',
                'GRANDE',
                'GIGANTE'
                );
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'animal_tipo') THEN
            CREATE TYPE animal_tipo AS ENUM (
                'CACHORRO',
                'GATO'
                );
        END IF;
    END$$;

CREATE TABLE adocoes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status          adocao_status NOT NULL DEFAULT 'PENDENTE',
    observacoes     TEXT,
    usuario_id      BIGINT NOT NULL,
    animal_id       BIGINT NOT NULL,
    concluido_em    TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_adocoes PRIMARY KEY (id)
);

CREATE TABLE animais
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome                       VARCHAR(255) NOT NULL,
    tipo                       animal_tipo NOT NULL,
    descricao                  TEXT,
    data_nascimento_aproximada DATE,
    sexo                       animal_sexo NOT NULL,
    porte                      animal_porte NOT NULL,
    pelagem                    animal_pelagem NOT NULL,
    imagem_path                VARCHAR(255),
    disponivel_para_adocao     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_animais PRIMARY KEY (id)
);

CREATE TABLE animais_caracteristicas
(
    animal_id         BIGINT  NOT NULL,
    caracteristica_id INTEGER NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_animais_caracteristicas PRIMARY KEY (animal_id, caracteristica_id)
);

CREATE TABLE caracteristicas
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    CONSTRAINT pk_caracteristicas PRIMARY KEY (id)
);

CREATE TABLE enderecos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id  BIGINT NOT NULL,
    cep         VARCHAR(255) NOT NULL,
    logradouro  VARCHAR(255) NOT NULL,
    complemento VARCHAR(255),
    bairro      VARCHAR(255) NOT NULL,
    localidade  VARCHAR(255) NOT NULL,
    uf          VARCHAR(255) NOT NULL,
    CONSTRAINT pk_enderecos PRIMARY KEY (id)
);

CREATE TABLE questionarios
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sexo               animal_sexo,
    porte              animal_porte,
    pelagem            animal_pelagem,
    ideal_casa         BOOLEAN,
    gosta_crianca      BOOLEAN,
    cao_guarda         BOOLEAN,
    brincalhao         BOOLEAN,
    necessidade_correr BOOLEAN,
    queda_pelo         BOOLEAN,
    tende_latir        BOOLEAN,
    usuario_id         BIGINT NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_questionarios PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    senha           VARCHAR(255) NOT NULL,
    cpf             VARCHAR(11),
    tipo            VARCHAR(255) NOT NULL,
    telefone        VARCHAR(255),
    genero          VARCHAR(50),
    data_nascimento DATE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    deletado_em     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE enderecos
    DROP CONSTRAINT IF EXISTS uc_enderecos_user;
ALTER TABLE enderecos
    ADD CONSTRAINT uc_enderecos_usuario UNIQUE (usuario_id);

ALTER TABLE questionarios
    DROP CONSTRAINT IF EXISTS uc_questionarios_user;
ALTER TABLE questionarios
    ADD CONSTRAINT uc_questionarios_usuario UNIQUE (usuario_id);

ALTER TABLE usuarios
    DROP CONSTRAINT IF EXISTS uc_usuarios_email;
ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_email UNIQUE (email);

ALTER TABLE usuarios
    DROP CONSTRAINT IF EXISTS uc_usuarios_cpf;

ALTER TABLE adocoes
    DROP CONSTRAINT IF EXISTS FK_ADOCOES_ON_ANIMAL;
ALTER TABLE adocoes
    ADD CONSTRAINT FK_ADOCOES_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animais (id);

ALTER TABLE adocoes
    DROP CONSTRAINT IF EXISTS FK_ADOCOES_ON_USER;
ALTER TABLE adocoes
    ADD CONSTRAINT FK_ADOCOES_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);

ALTER TABLE animais_caracteristicas
    DROP CONSTRAINT IF EXISTS FK_ANIMAIS_CARACTERISTICAS_ON_ANIMAL;
ALTER TABLE animais_caracteristicas
    ADD CONSTRAINT FK_ANIMAIS_CARACTERISTICAS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animais (id);

ALTER TABLE animais_caracteristicas
    DROP CONSTRAINT IF EXISTS FK_ANIMAIS_CARACTERISTICAS_ON_CARACTERISTICA;
ALTER TABLE animais_caracteristicas
    ADD CONSTRAINT FK_ANIMAIS_CARACTERISTICAS_ON_CARACTERISTICA FOREIGN KEY (caracteristica_id) REFERENCES caracteristicas (id);

ALTER TABLE enderecos
    DROP CONSTRAINT IF EXISTS FK_ENDERECOS_ON_USER;
ALTER TABLE enderecos
    ADD CONSTRAINT FK_ENDERECOS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);

ALTER TABLE questionarios
    DROP CONSTRAINT IF EXISTS FK_QUESTIONARIOS_ON_USER;
ALTER TABLE questionarios
    ADD CONSTRAINT FK_QUESTIONARIOS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);
