DROP TABLE IF EXISTS questionarios;

CREATE TYPE questionario_moradia AS ENUM (
    'CASA_QUINTAL_TOTALMENTE_FECHADO',
    'CASA_QUINTAL_ABERTO',
    'CASA_SEM_QUINTAL',
    'APARTAMENTO'
);

CREATE TABLE questionarios
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    moradia                       questionario_moradia,
    telas_protecao                BOOLEAN,
    todos_de_acordo               BOOLEAN,
    qtd_caes                      INTEGER DEFAULT 0,
    qtd_gatos                     INTEGER DEFAULT 0,
    qtd_outros                    INTEGER DEFAULT 0,
    ciente_custos                 BOOLEAN,
    termo_compromisso_longo_prazo BOOLEAN,
    termo_saude_bem_estar         BOOLEAN,
    termo_paciencia_adaptacao     BOOLEAN,
    usuario_id                    BIGINT NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                    TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_questionarios PRIMARY KEY (id),

    CONSTRAINT uq_questionarios_usuario_id UNIQUE (usuario_id),

    CONSTRAINT fk_questionarios_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);