-- 1. LIMPEZA (Drop & Recreate)
DROP TABLE IF EXISTS questionarios CASCADE;

DROP TYPE IF EXISTS questionario_moradia CASCADE;
DROP TYPE IF EXISTS questionario_preferencia_idade CASCADE;
DROP TYPE IF EXISTS questionario_preferencia_sexo CASCADE;
DROP TYPE IF EXISTS questionario_tem_criancas CASCADE;
DROP TYPE IF EXISTS questionario_preferencia_porte CASCADE; -- Garante limpeza do tipo antigo

-- 2. CRIAÇÃO DE TIPOS (ENUMS)
CREATE TYPE questionario_preferencia_sexo AS ENUM ('MACHO', 'FEMEA', 'INDIFERENTE');
CREATE TYPE questionario_tem_criancas AS ENUM ('NAO', 'CRIANCAS_PEQUENAS', 'CRIANCAS_MAIORES');

-- Moradia continua como Categoria (Texto no banco)
CREATE TYPE questionario_moradia AS ENUM ('KITNET', 'APARTAMENTO_PEQUENO', 'APARTAMENTO_GRANDE', 'CASA_SEM_QUINTAL', 'CASA_COM_QUINTAL');

-- 3. CRIAÇÃO DA TABELA
CREATE TABLE questionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id BIGINT NOT NULL,

    -- Enums (Categorias)
    sexo questionario_preferencia_sexo,
    tem_criancas questionario_tem_criancas,
    moradia questionario_moradia,

    -- Escala Numérica (Porte definido apenas uma vez como INTEGER)
    porte INTEGER,

    -- Demais Escalas
    nivel_queda_pelo INTEGER,
    nivel_latido INTEGER,
    instinto_guarda INTEGER,
    nivel_energia INTEGER,
    tempo_disponivel INTEGER,
    experiencia_pets INTEGER,

    -- Contexto (Booleanos)
    disposicao_necessidades_especiais BOOLEAN,
    possui_gatos BOOLEAN,
    possui_caes BOOLEAN,

    -- Termos
    ciente_custos BOOLEAN,
    termo_compromisso_longo_prazo BOOLEAN,
    termo_saude_bem_estar BOOLEAN,
    termo_paciencia_adaptacao BOOLEAN,
    termo_vistoria BOOLEAN,
    termo_devolucao_nao_abandono BOOLEAN,
    termo_legislacao_posse_responsavel BOOLEAN,

    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_questionarios PRIMARY KEY (id),
    CONSTRAINT uq_questionarios_usuario_id UNIQUE (usuario_id),
    CONSTRAINT fk_questionarios_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);